# Generated by Django 4.0 on 2022-01-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_rename_assignedtaskdescription_assignedtaskdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernote',
            name='note_added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
